- pkg:maven/com.arpnetworking.metrics/prometheus-remote-protocol@1.0.0
- pkg:maven/com.arpnetworking.metrics/prometheus-remote-protocol@1.0.0?classifier=sources
- pkg:maven/com.arpnetworking.metrics/prometheus-remote-protocol@1.0.1
- pkg:maven/com.arpnetworking.metrics/prometheus-remote-protocol@1.0.1?classifier=sources
