- pkg:maven/org.springframework.cloud/kafka-configmap-test-app@3.1.6?classifier=sources
- pkg:maven/org.springframework.cloud/kafka-configmap-test-app@3.2.2?classifier=sources
- pkg:maven/org.springframework.cloud/kafka-configmap-test-app@5.0.0-M1?classifier=sources
- pkg:maven/org.springframework.cloud/kafka-configmap-test-app@5.0.0-M2?classifier=sources
