- pkg:maven/pl.nort/config@1.0.0
- pkg:maven/pl.nort/config@1.0.0?classifier=sources
- pkg:maven/pl.nort/config@1.1.0
- pkg:maven/pl.nort/config@1.1.0?classifier=sources
- pkg:maven/pl.nort/config@2.0.0
- pkg:maven/pl.nort/config@2.0.0?classifier=sources
- pkg:maven/pl.nort/config@2.0.1
- pkg:maven/pl.nort/config@2.0.1?classifier=sources
