- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.12@0.6.0
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.12@0.6.0?classifier=sources
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.12@0.6.1
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.12@0.6.1?classifier=sources
