- pkg:maven/de.fraunhofer.iosb.io.moquette/moquette-metrics-prometheus@0.18.1?classifier=sources
- pkg:maven/de.fraunhofer.iosb.io.moquette/moquette-metrics-prometheus@0.18.2?classifier=sources
- pkg:maven/de.fraunhofer.iosb.io.moquette/moquette-metrics-prometheus@0.18.3?classifier=sources
