- pkg:maven/de.gesellix/docker-compose@2021-02-19T23-58-16?classifier=sources
- pkg:maven/de.gesellix/docker-compose@2021-04-07T12-44-08?classifier=sources
- pkg:maven/de.gesellix/docker-compose@2021-04-10T11-53-34?classifier=sources
- pkg:maven/de.gesellix/docker-compose@2021-04-22T00-21-01?classifier=sources
- pkg:maven/de.gesellix/docker-compose@2021-06-06T19-36-20?classifier=sources
- pkg:maven/de.gesellix/docker-compose@2021-08-06T13-40-45?classifier=sources
- pkg:maven/de.gesellix/docker-compose@2021-08-27T18-26-00?classifier=sources
- pkg:maven/de.gesellix/docker-compose@2021-09-06T09-13-00?classifier=sources
- pkg:maven/de.gesellix/docker-compose@2021-09-21T08-00-00?classifier=sources
