- pkg:maven/com.alibaba.otter/canal.prometheus@1.1.0
- pkg:maven/com.alibaba.otter/canal.prometheus@1.1.0?classifier=sources
- pkg:maven/com.alibaba.otter/canal.prometheus@1.1.1
- pkg:maven/com.alibaba.otter/canal.prometheus@1.1.1?classifier=sources
