- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.0
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.0?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.1
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.1?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.2
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.2?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.0
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.0?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.1
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.1?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.2
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.2?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.3
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.3?classifier=sources
