- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.0
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.0?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.1
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.1?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.2
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.4.2?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.0
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.0?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.1
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.1?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.2
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.2?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.3
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.3?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.4
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.4?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.5.5?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.6.0?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.6.1?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.6.2?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.7.0?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.7.1?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.7.2?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.7.3?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.7.4?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.7.5?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.8.0?classifier=sources
- pkg:maven/eu.maveniverse.maven.njord.publisher/deploy@0.8.1?classifier=sources
