- pkg:maven/com.avast/sst-micrometer-prometheus-pureconfig_2.13@0.14.0
- pkg:maven/com.avast/sst-micrometer-prometheus-pureconfig_2.13@0.14.0?classifier=sources
- pkg:maven/com.avast/sst-micrometer-prometheus-pureconfig_2.13@0.14.2
- pkg:maven/com.avast/sst-micrometer-prometheus-pureconfig_2.13@0.14.2?classifier=sources
- pkg:maven/com.avast/sst-micrometer-prometheus-pureconfig_2.13@0.14.3
- pkg:maven/com.avast/sst-micrometer-prometheus-pureconfig_2.13@0.14.3?classifier=sources
