- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard@1.3.10?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard@1.3.5?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard@1.3.6?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard@1.3.7?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard@1.3.8?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard@1.3.9?classifier=sources
