- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.3.0
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.3.0?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.0
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.0?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.1
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.1?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.2
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.2?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.3
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.3?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.5.0
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.5.0?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.6.0
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.6.0?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.7.0
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.7.0?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.8.0
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.8.0?classifier=sources
