- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.3.0
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.3.0?classifier=sources
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.0
- pkg:maven/org.apache.camel/camel-micrometer-prometheus@4.4.0?classifier=sources
