- pkg:maven/de.objekt-kontor/config@1.0.0
- pkg:maven/de.objekt-kontor/config@1.0.0?classifier=sources
- pkg:maven/de.objekt-kontor/config@1.1.0
- pkg:maven/de.objekt-kontor/config@1.1.0?classifier=sources
- pkg:maven/de.objekt-kontor/config@1.1.1
- pkg:maven/de.objekt-kontor/config@1.1.1?classifier=sources
- pkg:maven/de.objekt-kontor/config@1.2.0
- pkg:maven/de.objekt-kontor/config@1.2.0?classifier=sources
- pkg:maven/de.objekt-kontor/config@1.2.1
- pkg:maven/de.objekt-kontor/config@1.2.1?classifier=sources
