- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.29.0?classifier=sources
- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.29.1?classifier=sources
- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.29.2?classifier=sources
