- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.29.0?classifier=sources
- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.29.1?classifier=sources
- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.29.2?classifier=sources
- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.29.3?classifier=sources
- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.29.4?classifier=sources
- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.30.0?classifier=sources
- pkg:maven/com.linecorp.armeria/armeria-prometheus1@1.30.1?classifier=sources
